### ISSUE TITLE
Android Integration For Kotlin Not working In Flutter Latest

### ISSUE THREAD

**Issue by asifakhtar98** [WebEngage/webengage-flutter#26] opened 2022-11-28 05:31 UTC
If you are using flutter latest 3.3.9 with android kotlin configuration you will face errors on build when implementing WebEngagePlugin, please have a look into it.

**Comment by SarthakWebEngage** [comment] 2022-12-21 06:09
Hi @asifakhtar98,
Can you help us with the necessary logs/details ?

**Comment by mahanabd** [comment] 2023-01-05 07:50
@MilindWebEngage 
thanks for your fast supporting.
I just wanted to ask you a question.
Is there a problem if I extend MainApplication from FlutterFragmentActivity with FlutterApplication?

**Comment by mahanabd** [comment] 2023-01-05 08:37
this problem is fix now in document:
https://docs.webengage.com/docs/flutter

**Comment by MilindWebEngage** [comment] 2023-01-05 09:46
> @MilindWebEngage thanks for your fast supporting. I just wanted to ask you a question. Is there a problem if I extend MainApplication from FlutterFragmentActivity with FlutterApplication?

You need to extend MainApplication with FlutterApplication only as it is a base class for android. 
If you want to extend with FlutterFragmentActivity create a new class and extends with it, and mention that activity in manifest file but the **_WebEngage initialise will be in MainApplication only_**

@mahanabd Please try to reply on the thread on which you have commented previously.
As it will be easy for us and other devs to track the different issue.
As your previous thread was on [#24](https://github.com/WebEngage/webengage-flutter/issues/24)

**Comment by MilindWebEngage** [comment] 2023-01-05 09:48
> this problem is fix now in document: https://docs.webengage.com/docs/flutter

for thread [#24 ](https://github.com/WebEngage/webengage-flutter/issues/24)

**Comment by SarthakWebEngage** [comment] 2023-03-13 06:46
Due to the lack of activity, the issue is closed.

**Closed by SarthakWebEngage** 2023-03-13 06:46 UTC
